name: Create Album Post
description: Creates a PR to add a new album post to the blog.

on:
  workflow_dispatch:
    inputs:
      album_title:
        type: string
        required: true
        description: Title of the album.
      artist_name:
        type: string
        required: true
        description: Name of the artist.

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest
    environment: deployment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - id: stack
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: --fast # No pedantic for now

      - name: Run
        id: run
        run: |
          BRANCH_NAME=$(echo "${{ github.event.inputs.album_title }}-${{ github.event.inputs.artist_name }}" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9-')
          stack exec pull-album-info "${{ github.event.inputs.artist_name }}" "${{ github.event.inputs.album_title }}" $BRANCH_NAME

          # Switch to bot account
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
        env:
          DISCOG_KEY: ${{ secrets.DISCOG_KEY }}
          DISCOG_SECRET: ${{ secrets.DISCOG_SECRET }}

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ steps.run.outputs.branch_name }}
          base: main
          title: post/${{ steps.run.outputs.branch_name }}
          body-path: '${{ github.workspace }}/drafts/${{ steps.run.outputs.branch_name }}'
          labels: 'post'
