name: Deploy personal website

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'posts/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: deployment
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - id: stack
        uses: freckle/stack-action@v5
        with:
          stack-build-arguments: --fast # No pedantic for now

      - run: stack exec site build

      - run: |
          if [[ $(git status --porcelain docs/) ]]; then
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add docs/
            if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
              git commit -m "Update site at $(date)"
            else
              new_post=$(git diff --name-only HEAD^ | grep 'posts/')
              git commit -m "Add new post: ${new_post}"
            fi
            git push origin main
          else
            echo "No changes in docs/ directory"
          fi